### ISSUE TITLE
File format of logic analyzer

### ISSUE THREAD

**Issue by Jeekate** [SebiTimeWaster/ICN2053_ESP32_LedWall#4]
I cannot open *.sr file, neither know witch app can recognize it.
Could you please tell me what branch of logic analyzer you use? or how to open the capture file [64x64_50fps.sr](https://github.com/SebiTimeWaster/ICN2053_ESP32_LedWall/blob/master/Logic_Analyzer/64x64_50fps.sr)

**Comment by SebiTimeWaster** [comment]
in the readme i stated:

"- In this repo in the "Logic_Analyzer" directory one will find Logic Analyzer recordings of the data sent to the panels, one can open them with the open source tool [PulseView](https://sigrok.org/wiki/PulseView). I only have a 8 channel 24Mhz Logic Analyzer so not all pins are recorded."
